### ISSUE TITLE
Unable to connect to gateway

### ISSUE THREAD

**Issue by barryvdh** [zendframework/ZendService_Apple_Apns#30]
When I try to connect to the gateway, I get the following errors:

> Warning: stream_socket_client(): Failed to enable crypto in /var/www/html/apn/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Client/AbstractClient.php on line 105
> Warning: stream_socket_client(): unable to connect to ssl://gateway.sandbox.push.apple.com:2195 (Unknown error) in /var/www/html/apn/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Client/AbstractClient.php on line 105

This is on both PHP 5.5 and PHP 5.6, running CentOS 6.
I tried it on a windows XAMPP stack, and there the connection works. So I assume the certificates/keys are correct.

I also tried `openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert certificate.pem -key certificate.pem` and `telnet gateway.sandbox.push.apple.com 2195`, which both seem to be connection properly. Also tried disabling `verify_peer` in the SSL options or the protocol to `tls://`, but doesn't matter..

Do you have any suggestions? Tried it on 2 different CentOS servers.

**Comment by mwillbanks** [comment]
@barryvdh generally this means that your SSL configuration options are not set properly.  Did you set a certificate but did not set a passphrase on a certificate that had one? Or visa-versa?  Also double check the path.  I have not been able to replicate this myself and I am assuming that php has openssl support turned on?

**Comment by barryvdh** [comment]
I exported it without passphrase again and it does seem to work now. Thanks!
