### ISSUE TITLE
Ignored error responses

### ISSUE THREAD

**Issue by UFOMelkor** [zendframework/ZendService_Apple_Apns#35]
I've got problems with `AbstractClient::read()` especially with [$stream_meta_data['unread_bytes']](https://github.com/zendframework/ZendService_Apple_Apns/blob/0a36bee030ad8c79b529f578e3e33254641b5853/library/ZendService/Apple/Apns/Client/AbstractClient.php#L156).

There has been an invalid token within one connection that was not detected. I debugged it with the following output of

`feof($this->socket)`: `true`

`fread($this->socket)`: `&#0;&#0;&#0;`

`stream_get_meta_data($this->socket)`:
```
[
    'stream_type' => 'tcp_socket/ssl',
    'mode'  => 'r+',
    'unread_bytes' => 0,
    'seekable' => false,
    'timed_out' => false,
    'blocked' => false,
    'eof' => false
]
```

So while `feof` and `fread` both provide the ‘right’ data, it does not read the stream because `stream_get_meta_data` returns invalid data.

The error occurred on on PHP 5.6.9 (openSUSE 13.2) and PHP 5.6.10 (Ubuntu 14.04).

**Comment by mwillbanks** [comment]
Fixed with #38
