### ISSUE TITLE
Implement HTTP/2 protocol for push notifications

### ISSUE THREAD

**Issue by khrizt** [zendframework/ZendService_Apple_Apns#45]
Apple added support 2 months ago to the HTTP/2 protocol for sending push notifications, is there any plans to include it in the Apple Apns service?

**Comment by arubacao** [comment]
+1

**Comment by ga46jac** [comment]
+1

**Comment by harri121** [comment]
+1

**Comment by barryvdh** [comment]
Perhaps look at https://github.com/zendframework/ZendService_Google_Gcm and make a PR using zend-http?

**Comment by barryvdh** [comment]
Docs: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html
Would require a big rewrite probably, because the error statuses have been changed etc.

**Comment by staelche** [comment]
I am working currently on a rewrite based on curl. If you have still a week time or so I can provide a PR.

Is it possible to use zend-http to make HTTP/2 requests. The AbstractMessage class only defines HTTP version 1 and 1.1. So first the http lib would need to be updated, I guess. Which sounds like a bigger task as well.

**Comment by staelche** [comment]
If you want to you can have a look at the [http/2 implementation](https://github.com/c24holdingit/ZendService_Apple_Apns).

Maybe it suits you and you want to merge it...

**Comment by arthurkirkosa** [comment]
Any news on this merge?

**Comment by montolio** [comment]
Any news here?

**Comment by danicastanos** [comment]
+1

**Comment by ahfeel** [comment]
+1

**Comment by honarkhah** [comment]
+1

**Comment by Ocramius** [comment]
Closing: this package is unmaintained, don't expect maintainers of ZF to send a PR.
If you need this functionality, send a PR (tested!) against `master` and it shall be merged if appropriate.

**Comment by khrizt** [comment]
I developed a library that works with GCM and HTTP/2 APN, if anyone wants to try you can find it at https://github.com/khrizt/PushNotiphications

**Comment by seyfer** [comment]
@staelche, why you haven't made a PR?
