### ISSUE TITLE
Use zend json v3

### ISSUE THREAD

**Issue by adaojunior** [zendframework/ZendService_Apple_Apns#50]
I wonder if this package could support zend json version 3. I tried to use this package but I got a error because other package is already using zend json version 3.

**Comment by adamlundrigan** [comment]
Not terribly familiar with this component but it looks to me that none of the BC breaks between v2 and v3 affect this component's use of Zend\Json so it should just be a matter of updating the version constrain in the composer.json file to `~2.0 || ^3.0`, or similar.

**Comment by adaojunior** [comment]
@adamlundrigan I made the change you suggested and seems like the tests passed.

**Comment by akaneru** [comment]
Hi @adamlundrigan could you please accept the related pull request from @adaojunior?
That will allow us to upgrade the ZF to the new version without loosing that important module :)

Best regards

**Comment by Ocramius** [comment]
Merged, but don't expect releases ;-)

**Comment by akaneru** [comment]
Thank you so much :)

**Comment by Ocramius** [comment]
@adaojunior @akaneru this package is officially unmaintained, so there won't be more releases of it. Yes, you will have to rely on `dev-master`.

**Comment by adaojunior** [comment]
ok, thanks
