### ISSUE TITLE
wrong json format when using custom data

### ISSUE THREAD

**Issue by shaljam** [zendframework/ZendService_Apple_Apns#52]
json is generated wrong so the custom message is not received on iOS device.

example output payload generated:
`{"custom-data":{"c1":"one","c2":"two"},"aps":{"sound":"bingbong.aiff","content-available":1,"category":"code1"}}`

received notification on device:
`["sound": bingbong.aiff, "category": code1, "content-available": 1]`

how payload should be:
`{"aps":{"custom-data":{"c1":"one","c2":"two"},"sound":"bingbong.aiff","content-available":1,"category":"code1"}}`

received notification on device:
`["custom-data": {
    c1 = one;
    c2 = two;
}, "sound": bingbong.aiff, "content-available": 1, "category": code1]`

fix is simple by changing line `390` of file ` ZendService_Apple_Apns/library/ZendService/Apple/Apns/Message.php`
from
`$message = array_merge($this->custom, $message);`
to 
`$aps = array_merge($this->custom, $aps);`

**Comment by DannyvdSluijs** [comment]
@shaljam Based on the following Apple developer page (https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1)

the custom content isn't inside the "app" key.

**Comment by shaljam** [comment]
@DannyvdSluijs I see. But that was what I tested.
