### ISSUE TITLE
Release version with support for zend-json v3

### ISSUE THREAD

**Issue by kimhemsoe** [zendframework/ZendService_Apple_Apns#58]
Can i help with anything to make this happen?

**Comment by patrice-guillemette** [comment]
We would need another release with zend-json V3 instead of V2. This would make it work with the last Laravel release.

**Comment by seyfer** [comment]
Isn't it closed by https://github.com/zendframework/ZendService_Apple_Apns/pull/51 ?

**Comment by kimhemsoe** [comment]
Still need a new release :)

**Comment by webimpress** [comment]
Released with 1.3.0, the latest one is 1.4.1. Closing now. Thanks!
